import type { Locale } from './routes';
// Slugs remain stable across locales; only display labels are localized.
const labels: Record<string, [string, string, string]> = {
  '2026-cybersecurity-conference': ['2026 資安大會', '2026 Cybersecurity Conference', '2026 サイバーセキュリティカンファレンス'],
  embedded: ['嵌入式', 'Embedded', '組み込み'], medical: ['醫療', 'Medical', '医療'], systems: ['系統', 'Systems', 'システム'], life: ['生活', 'Life', '日常'], activities: ['活動', 'Activities', '活動'],
  ai: ['人工智慧', 'AI', '人工知能'], 'ai-security': ['AI 資安', 'AI Security', 'AI セキュリティ'], 'ai-soc': ['AI SOC', 'AI SOC', 'AI SOC'],
  'blue-team': ['藍隊', 'Blue Team', 'ブルーチーム'], career: ['職涯', 'Career', 'キャリア'], choices: ['選擇', 'Choices', '選択'], codex: ['Codex', 'Codex', 'Codex'], competition: ['競賽', 'Competition', '競技大会'], compliance: ['法遵', 'Compliance', 'コンプライアンス'], ctf: ['CTF', 'CTF', 'CTF'], cybersec: ['CYBERSEC', 'CYBERSEC', 'CYBERSEC'], cybersecurity: ['資安', 'Cybersecurity', 'サイバーセキュリティ'], dfir: ['數位鑑識與事件應變', 'DFIR', 'デジタルフォレンジックとインシデント対応'], 'edge-ai': ['邊緣 AI', 'Edge AI', 'エッジ AI'], engineering: ['工程', 'Engineering', 'エンジニアリング'], 'financial-security': ['金融資安', 'Financial Security', '金融セキュリティ'], frc: ['FRC', 'FRC', 'FRC'], future: ['未來', 'Future', '未来'], growth: ['成長', 'Growth', '成長'], healthcare: ['醫療', 'Healthcare', '医療'], 'healthcare-medical-iot': ['醫療與醫療物聯網', 'Healthcare / Medical IoT', '医療と医療 IoT'], 'high-school-life': ['高中生活', 'High School Life', '高校生活'], homelab: ['Homelab', 'Homelab', 'Homelab'], 'incident-response': ['事件應變', 'Incident Response', 'インシデント対応'], 'infosec-taiwan': ['InfoSec Taiwan', 'InfoSec Taiwan', 'InfoSec Taiwan'], introduction: ['自我介紹', 'Introduction', '自己紹介'], journey: ['旅程', 'Journey', '歩み'], 'malware-analysis': ['惡意程式分析', 'Malware Analysis', 'マルウェア解析'], 'medical-cybersecurity': ['醫療資安', 'Medical Cybersecurity', '医療サイバーセキュリティ'], memories: ['回憶', 'Memories', '思い出'], 'my-story': ['我的故事', 'My Story', '自分の物語'], 'ot-security': ['OT 資安', 'OT Security', 'OT セキュリティ'], personal: ['個人記事', 'Personal', '個人の記録'], 'post-quantum-cryptography': ['後量子密碼學', 'Post-quantum Cryptography', '耐量子暗号'], projects: ['專案', 'Projects', 'プロジェクト'], 'raspberry-pi': ['Raspberry Pi', 'Raspberry Pi', 'Raspberry Pi'], reflection: ['反思', 'Reflection', '振り返り'], research: ['研究', 'Research', '研究'], 'responsible-security-culture': ['負責任的資安文化', 'Responsible Security Culture', '責任あるセキュリティ文化'], retail: ['零售業', 'Retail', '小売業'], robotics: ['機器人', 'Robotics', 'ロボティクス'], security: ['資安', 'Security', 'セキュリティ'], 'security-culture': ['資安文化', 'Security Culture', 'セキュリティ文化'], 'sme-security': ['中小企業資安', 'SME Security', '中小企業のセキュリティ'], soc: ['SOC', 'SOC', 'SOC'], students: ['學生', 'Students', '学生'], 'windows-forensics': ['Windows 鑑識', 'Windows Forensics', 'Windows フォレンジック'], 'windows-malware': ['Windows 惡意程式', 'Windows Malware', 'Windows マルウェア'], wireshark: ['Wireshark', 'Wireshark', 'Wireshark'], 'zero-trust': ['零信任', 'Zero Trust', 'ゼロトラスト'], '近況': ['近況', 'Life Updates', '近況'],
};
export const localizedTopic = (slug: string, fallback: string, locale: Locale): string => labels[slug]?.[{ zh: 0, en: 1, ja: 2 }[locale]] ?? fallback;
