import type { Locale } from './routes';
const zh = {
  nav: { articles: '文章', topics: '主題', experience: '經歷', archive: '文章彙整', about: '關於', menu: '選單', label: '主要導覽', language: '網站語言' },
  footer: { label: '頁尾導覽', notes: '筆記' },
  common: { skip: '跳至主要內容', all: '全部', categories: '文章分類', selectCategory: '選擇分類', empty: '此分類目前沒有文章。', notes: '篇文章', newest: '由新到舊', published: '已發布文章', previous: '上一篇', next: '下一篇', back: '返回文章列表', contents: '本頁目錄', translations: '語言版本', languages: { zh: '繁體中文', en: '英文', ja: '日文' } },
  home: { eyebrow: '把故事留下來', intro: ['筆記、實驗，', '以及值得留下的事。'], writing: '01 · 書寫', latest: '最新文章', viewAll: '查看所有文章 →', more: '更多文章', archive: '文章彙整 →', sections: '02 · 分類', thread: '沿著主題閱讀。', browse: '探索更多主題 →', by: '作者 Nagi。' },
  about: { title: '關於', description: '關於 Nagi：生活、探索，以及把想法做出來的過程。', eyebrow: '關於 · Nagi', heading: '安靜地做，慢慢地累積。', motto: '「我相信我的故事，有一天會被別人看見。」', paragraphs: ['我是 Nagi。這裡記錄我走過的路、遇見的人，以及把想法慢慢做出來的過程。', '我喜歡做東西，也在學習先理解問題，再決定使用什麼技術。比起把新工具全部放進專案，我更想知道：這件事能為誰解決什麼問題？', '目前的興趣包括醫療科技、Edge AI、AI Agents、嵌入式系統與 Homelab。資安是其中一個持續探索的方向；生活、團隊與那些改變想法的經驗，也同樣值得留下。', '我希望自己保持好奇、保有判斷力，也記得那些一起走過的人。'], experience: '參與過的競賽與活動整理在', home: '。其他筆記請見', end: '。' },
  experience: { title: '經歷', description: 'Nagi 參與過的競賽、研習、研討會與技術活動。', eyebrow: '競賽與活動', intro: '整理參與過的競賽、研習、研討會與技術活動。', read: '閱讀相關文章 →', sections: { competitions: '競賽', training: '研習與培訓', conferences: '研討會與社群', leadership: '帶隊、教學與角色' }, events: [{ name: 'FRC 季後賽', kind: '機器人競賽', role: '帶隊、賽前維修與團隊協作', category: 'competitions' }, { name: 'InfoSec Taiwan 2026', kind: '研討會', role: '參訪與產業觀察', category: 'conferences' }, { name: '2026 資安大會', kind: '研討會', role: '參訪與跨領域探索', category: 'conferences' }] },
  articles: { title: '文章', eyebrow: '文章索引', description: '人生經驗、資安、專案，以及目前正在探索的研究。', fallback: '本文尚無繁體中文版，目前顯示可用版本。' },
  archive: { title: '文章彙整', eyebrow: '按時間閱讀', description: '依年份與月份整理的文章。' },
  topics: { title: '主題', eyebrow: '主題與線索', intro: '從 CTF、FRC 到 AI 與醫療，沿著細部主題閱讀。文章的四個主要分類，請見', end: '。', related: '相關文章', topic: '主題', legacy: '舊主題索引', description: '同一個主題，可以出現在不同的人生經驗、資安筆記、專案與研究中。', legacyDescription: '此索引也保留舊主題中的文章，不代表目前的主要分類。', browse: '瀏覽文章 →' },
  categories: { life: { title: '人生經驗', subtitle: '生活與成長', description: '成長、生活與親身經歷。' }, security: { title: '資安', subtitle: '分析與探索', description: '安全分析、CTF 技術筆記與安全探索。' }, projects: { title: '專案', subtitle: '實作與開發', description: '實際做出的系統、原型與開發紀錄。' }, research: { title: '研究', subtitle: '問題與實驗', description: '目前正在追問的問題、實驗與研究方向。' } },
};
type Dictionary = typeof zh;
const en: Dictionary = {
  nav: { articles: 'Articles', topics: 'Topics', experience: 'Experience', archive: 'Archive', about: 'About', menu: 'Menu', label: 'Main navigation', language: 'Site language' },
  footer: { label: 'Footer navigation', notes: 'Notes' },
  common: { skip: 'Skip to content', all: 'All', categories: 'Article categories', selectCategory: 'Select category', empty: 'No articles in this category yet.', notes: 'articles', newest: 'Newest first', published: 'Published articles', previous: 'Previous', next: 'Next', back: 'Back to Articles', contents: 'On this page', translations: 'Language versions', languages: { zh: 'Traditional Chinese', en: 'English', ja: 'Japanese' } },
  home: { eyebrow: 'The longer record', intro: ['Notes, experiments,', 'and things worth keeping.'], writing: '01 · Writing', latest: 'Recent Articles', viewAll: 'View all articles \u2192', more: 'More writing', archive: 'Archive \u2192', sections: '02 \u00b7 Sections', thread: 'Follow a thread.', browse: 'Browse detailed topics \u2192', by: 'By Nagi.' },
  about: { title: 'About', description: 'About Nagi: life, exploration, and turning ideas into something real.', eyebrow: 'About \u00b7 Nagi', heading: 'Build quietly.', motto: '\u201cI believe that one day, someone will see my story.\u201d', paragraphs: ['I\u2019m Nagi. This is where I keep a record of the paths I\u2019ve taken, the people I\u2019ve met, and the ideas I\u2019m gradually bringing to life.', 'I enjoy making things, and I\u2019m learning to understand the problem before choosing the technology. Rather than fitting every new tool into a project, I want to ask: whose problem can this actually solve?', 'My interests include medical technology, Edge AI, AI agents, embedded systems, and my homelab. Cybersecurity is one ongoing thread; everyday life, teamwork, and experiences that change my perspective deserve a place here too.', 'I hope to stay curious, think for myself, and remember the people who have shared the journey.'], experience: 'You can find the competitions and events I\u2019ve taken part in under', home: '. For more notes, visit', end: '.' },
  experience: { title: 'Experience', description: 'Competitions, training, conferences, and technical activities.', eyebrow: 'Competitions & events', intro: 'Selected competitions, training, conferences, and technical activities.', read: 'Read the related article \u2192', sections: { competitions: 'Competitions', training: 'Training & Workshops', conferences: 'Conferences & Community', leadership: 'Leadership / Teaching / Roles' }, events: [{ name: 'FRC Off-season Competition', kind: 'Robotics competition', role: 'Team leadership, pre-match repairs, and collaboration', category: 'competitions' }, { name: 'InfoSec Taiwan 2026', kind: 'Conference', role: 'Attending and observing the industry', category: 'conferences' }, { name: '2026 Cybersecurity Conference', kind: 'Conference', role: 'Attending and exploring connections across disciplines', category: 'conferences' }] },
  articles: { title: 'Articles', eyebrow: 'Publication index', description: 'Life, security, projects, and research I\u2019m exploring.', fallback: 'This article is not yet available in English. Showing the original Chinese version.' },
  archive: { title: 'Archive', eyebrow: 'Chronology', description: 'Browse articles by year and month.' },
  topics: { title: 'Topics', eyebrow: 'Subjects & threads', intro: 'Explore topics from CTF and FRC to AI and healthcare. For the four main categories, see', end: '.', related: 'Related articles', topic: 'Topic', legacy: 'Earlier topic index', description: 'A topic can connect life experiences, security notes, projects, and research.', legacyDescription: 'This index also includes articles from the earlier topic structure; it does not represent the current main categories.', browse: 'Browse Articles \u2192' },
  categories: { life: { title: 'Life', subtitle: 'Living and learning', description: 'Growing up, everyday life, and firsthand experiences.' }, security: { title: 'Security', subtitle: 'Analysis and exploration', description: 'Security analysis, CTF notes, and exploration.' }, projects: { title: 'Projects', subtitle: 'Building and developing', description: 'Systems, prototypes, and development logs.' }, research: { title: 'Research', subtitle: 'Questions and experiments', description: 'Open questions, experiments, and research directions.' } },
};
const ja: Dictionary = {
  nav: { articles: '記事', topics: 'トピック', experience: '活動記録', archive: 'アーカイブ', about: '自己紹介', menu: 'メニュー', label: 'メインナビゲーション', language: 'サイトの言語' },
  footer: { label: 'フッターナビゲーション', notes: 'ノート' },
  common: { skip: '本文へ移動', all: 'すべて', categories: '記事のカテゴリー', selectCategory: 'カテゴリーを選択', empty: 'このカテゴリーにはまだ記事がありません。', notes: '件の記事', newest: '新しい順', published: '公開記事', previous: '前の記事', next: '次の記事', back: '記事一覧へ戻る', contents: '目次', translations: '言語別の記事', languages: { zh: '繁体字中国語', en: '英語', ja: '日本語' } },
  home: { eyebrow: '日々の記録を、少しずつ', intro: ['ノート、実験、', 'そして残しておきたいこと。'], writing: '01 · 書くこと', latest: '最近の記事', viewAll: 'すべての記事を見る →', more: 'ほかの記事', archive: 'アーカイブ →', sections: '02 · カテゴリー', thread: 'ひとつのテーマをたどる。', browse: 'トピックから探す →', by: 'Nagi が書いています。' },
  about: { title: '自己紹介', description: 'Nagi の日々、探究、そしてアイデアを形にするまでの記録。', eyebrow: '自己紹介 · Nagi', heading: '静かに、少しずつ形にする。', motto: '「いつか、誰かが自分の物語を見つけてくれると信じています。」', paragraphs: ['Nagi です。ここには、歩んできた道や出会った人たち、そしてアイデアを少しずつ形にしていく過程を記録しています。', 'ものを作るのが好きです。同時に、技術を選ぶ前に、まず問題を理解することを学んでいます。新しいツールをすべて詰め込むより、「誰の、どんな困りごとを解決できるのか」を大切にしたいと思っています。', '今は医療技術、Edge AI、AI エージェント、組み込みシステム、Homelab に関心があります。セキュリティは継続して探究しているテーマのひとつですが、日々の暮らしやチームでの経験、考え方が変わった出来事も残しておきたいと思っています。', '好奇心と自分で考える力を持ち続け、一緒に歩んできた人たちのことも忘れずにいたいです。'], experience: '参加した大会やイベントは', home: 'にまとめています。ほかのノートは', end: 'からご覧いただけます。' },
  experience: { title: '活動記録', description: '大会、研修、カンファレンス、技術活動の記録。', eyebrow: '大会とイベント', intro: '参加してきた大会、研修、カンファレンス、技術活動の記録です。', read: '関連記事を読む →', sections: { competitions: '競技大会', training: '研修・ワークショップ', conferences: 'カンファレンス・コミュニティ', leadership: 'チーム・指導・役割' }, events: [{ name: 'FRC オフシーズン大会', kind: 'ロボット競技大会', role: 'チームの指揮、試合前の修理、メンバーとの連携', category: 'competitions' }, { name: 'InfoSec Taiwan 2026', kind: 'カンファレンス', role: '見学と業界の動向調査', category: 'conferences' }, { name: '2026 サイバーセキュリティカンファレンス', kind: 'カンファレンス', role: '見学と分野をまたいだ探究', category: 'conferences' }] },
  articles: { title: '記事', eyebrow: '記事一覧', description: '日々の経験、セキュリティ、プロジェクト、そして探究中の研究について。', fallback: 'この記事の日本語版はまだありません。中国語の原文を表示しています。' },
  archive: { title: 'アーカイブ', eyebrow: '時系列で読む', description: '年と月から記事を探せます。' },
  topics: { title: 'トピック', eyebrow: 'テーマをたどる', intro: 'CTF や FRC から AI、医療まで、気になるテーマから読んでみてください。4つの主なカテゴリーは', end: 'でご覧いただけます。', related: '関連記事', topic: 'トピック', legacy: '以前のトピック一覧', description: 'ひとつのテーマが、日々の経験やセキュリティ、プロジェクト、研究をつなぎます。', legacyDescription: '以前の分類の記事も含む一覧です。現在の主要カテゴリーとは異なります。', browse: '記事一覧を見る →' },
  categories: { life: { title: '日々の経験', subtitle: '暮らしと成長', description: '成長、暮らし、そして自分で経験したこと。' }, security: { title: 'セキュリティ', subtitle: '分析と探究', description: 'セキュリティ分析、CTF の記録と探究。' }, projects: { title: 'プロジェクト', subtitle: '実装と開発', description: 'システムや試作品、開発の記録。' }, research: { title: '研究', subtitle: '問いと実験', description: '今向き合っている問い、実験、研究の方向性。' } },
};
export const ui: Record<Locale, Dictionary> = { zh, en, ja };
